export const QUESTIONS = [
  {
    id: 1,
    text: "What is React primarily used for?",
    options: [
      "Database management",
      "Building user interfaces",
      "Game development",
      "Operating systems",
    ],
    correctAnswer: "Building user interfaces",
  },
  {
    id: 2,
    text: "What language is React written in?",
    options: ["Python", "Java", "JavaScript", "C++"],
    correctAnswer: "JavaScript",
  },
  {
    id: 3,
    text: "What command is commonly used to create a new React app?",
    options: [
      "npm start react",
      "create-react-app",
      "npm create react-app",
      "react new app",
    ],
    correctAnswer: "create-react-app",
  },
  {
    id: 4,
    text: "What does JSX stand for?",
    options: [
      "Java Syntax Extension",
      "JavaScript XML",
      "JSON XML",
      "JavaScript Extension",
    ],
    correctAnswer: "JavaScript XML",
  },
  {
    id: 5,
    text: "Which symbol is used to embed JavaScript expressions in JSX?",
    options: ["()", "[]", "{}", "<>"],
    correctAnswer: "{}",
  },
  {
    id: 6,
    text: "What is a React component?",
    options: ["A database", "A reusable piece of UI", "A CSS file", "An API"],
    correctAnswer: "A reusable piece of UI",
  },
  {
    id: 7,
    text: "Which hook is used to manage state in a functional component?",
    options: ["useEffect", "useContext", "useState", "useRef"],
    correctAnswer: "useState",
  },
  {
    id: 8,
    text: "What hook is used to run side effects in React?",
    options: ["useState", "useMemo", "useEffect", "useCallback"],
    correctAnswer: "useEffect",
  },
  {
    id: 9,
    text: "What must every React component return?",
    options: ["CSS", "HTML", "JSX", "JSON"],
    correctAnswer: "JSX",
  },
  {
    id: 10,
    text: "What is the correct way to pass data to a child component?",
    options: ["State", "Hooks", "Props", "Context"],
    correctAnswer: "Props",
  },
  {
    id: 11,
    text: "What is the virtual DOM?",
    options: [
      "A copy of the real DOM",
      "A browser feature",
      "A database",
      "A server",
    ],
    correctAnswer: "A copy of the real DOM",
  },
  {
    id: 12,
    text: "Which method is used to render a list in React?",
    options: ["forEach", "map", "filter", "reduce"],
    correctAnswer: "map",
  },
  {
    id: 13,
    text: "Why are keys important when rendering lists?",
    options: [
      "For styling",
      "For performance and identity",
      "For routing",
      "For security",
    ],
    correctAnswer: "For performance and identity",
  },
  {
    id: 14,
    text: "What happens when state changes in React?",
    options: ["Page reloads", "Component re-renders", "App crashes", "Nothing"],
    correctAnswer: "Component re-renders",
  },
  {
    id: 15,
    text: "Which hook lets you reference a DOM element?",
    options: ["useState", "useRef", "useEffect", "useMemo"],
    correctAnswer: "useRef",
  },
  {
    id: 16,
    text: "What does lifting state up mean?",
    options: [
      "Deleting state",
      "Moving state to a parent component",
      "Using context",
      "Using Redux",
    ],
    correctAnswer: "Moving state to a parent component",
  },
  {
    id: 17,
    text: "Which file usually contains the root React component?",
    options: ["index.html", "main.js", "App.js", "style.css"],
    correctAnswer: "App.js",
  },
  {
    id: 18,
    text: "What is conditional rendering?",
    options: [
      "Rendering CSS conditionally",
      "Rendering based on a condition",
      "Routing pages",
      "Fetching data",
    ],
    correctAnswer: "Rendering based on a condition",
  },
  {
    id: 19,
    text: "Which operator is commonly used for conditional rendering?",
    options: ["+", "&&", "=", "++"],
    correctAnswer: "&&",
  },
  {
    id: 20,
    text: "What does useEffect depend on to re-run?",
    options: ["Props only", "State only", "Dependency array", "Context"],
    correctAnswer: "Dependency array",
  },
  {
    id: 21,
    text: "What is a controlled input?",
    options: [
      "Input managed by the DOM",
      "Input managed by state",
      "Disabled input",
      "Read-only input",
    ],
    correctAnswer: "Input managed by state",
  },
  {
    id: 22,
    text: "What does preventDefault do in events?",
    options: [
      "Stops rendering",
      "Stops default browser behavior",
      "Stops state updates",
      "Stops API calls",
    ],
    correctAnswer: "Stops default browser behavior",
  },
  {
    id: 23,
    text: "What is React Fragment used for?",
    options: [
      "Styling",
      "Grouping elements without extra nodes",
      "Routing",
      "State management",
    ],
    correctAnswer: "Grouping elements without extra nodes",
  },
  {
    id: 24,
    text: "What syntax is used for React fragments?",
    options: ["<> </>", "{} {}", "() ()", "[] []"],
    correctAnswer: "<> </>",
  },
  {
    id: 25,
    text: "Which hook improves performance by memoizing values?",
    options: ["useEffect", "useMemo", "useState", "useRef"],
    correctAnswer: "useMemo",
  },
  {
    id: 26,
    text: "What is prop drilling?",
    options: [
      "Deleting props",
      "Passing props through many components",
      "Using context",
      "Using hooks",
    ],
    correctAnswer: "Passing props through many components",
  },
  {
    id: 27,
    text: "Which tool is commonly used for routing in React?",
    options: ["Redux", "Axios", "React Router", "Tailwind"],
    correctAnswer: "React Router",
  },
  {
    id: 28,
    text: "What hook is used to access route parameters?",
    options: ["useParams", "useRoute", "usePath", "useMatch"],
    correctAnswer: "useParams",
  },
  {
    id: 29,
    text: "What does npm stand for?",
    options: [
      "Node Package Manager",
      "New Project Manager",
      "Node Program Module",
      "Next Package Manager",
    ],
    correctAnswer: "Node Package Manager",
  },
  {
    id: 30,
    text: "What is the purpose of useCallback?",
    options: ["Memoize functions", "Fetch data", "Update state", "Render JSX"],
    correctAnswer: "Memoize functions",
  },
  {
    id: 31,
    text: "What does strict mode do in React?",
    options: [
      "Improves performance",
      "Adds security",
      "Highlights potential problems",
      "Styles components",
    ],
    correctAnswer: "Highlights potential problems",
  },
  {
    id: 32,
    text: "Which lifecycle behavior does useEffect replace?",
    options: ["render", "componentDidMount", "setState", "constructor"],
    correctAnswer: "componentDidMount",
  },
  {
    id: 33,
    text: "What is a single-page application?",
    options: [
      "One HTML file",
      "Multiple HTML files",
      "One component",
      "One API",
    ],
    correctAnswer: "One HTML file",
  },
  {
    id: 34,
    text: "What tool is commonly used to style React apps?",
    options: ["Bootstrap", "Tailwind CSS", "Sass", "All of the above"],
    correctAnswer: "All of the above",
  },
  {
    id: 35,
    text: "What is the default export keyword used for?",
    options: [
      "Exporting multiple values",
      "Exporting a single main value",
      "Importing files",
      "Styling",
    ],
    correctAnswer: "Exporting a single main value",
  },
];
